OPENAI_API_KEY="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"
ASSISTANT_ID = "asst_MY8fb0gJvQwJyKgufGEs5Dja"
